# Generated by Django 4.0.5 on 2022-07-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transection', '0003_customer_history_delete_historicalcustomer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='history',
            new_name='last_transection',
        ),
    ]
