# Generated by Django 4.0.5 on 2022-07-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='history',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
