# Generated by Django 4.0.5 on 2022-07-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0004_rename_history_customer_last_transection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_transection',
        ),
    ]
