# Generated by Django 4.0.5 on 2022-07-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0004_remove_account_history_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='Record',
        ),
    ]
